### ISSUE TITLE
disassembly subview does not change.

### ISSUE THREAD

**Issue by combab0** [zyantific/IDASkins#1]
http://postimg.org/image/6gfs02tw3/

I use ida pro 6.6 and I have problem.

do I need any configuration?

as you know Ida provide 6 default subviews.

IDA View-A / Hex View-1 / Structures / Enums / Imports / Exports

Only two subview background changed properly. Imports, Exports

the other subviews remain default color background.

what should I do to use ida skin?

I used ida skin 1.2

**Comment by sh3dow** [comment]
I use IDA pro 6.6 and I have the some problem
http://i.imgur.com/eWuQArb.png

IDA View-A / Hex View-1 / Structures / Enums /   => background not changed
Imports / Exports => background changed

what should I do to use ida-skins ? plz explain step by step 
i use v1.3.0

**Comment by athre0z** [comment]
Your question is already answered above. Disassembly theming is an IDA feature, thus my plugin does not come with a skin for it. For a disassembly theme, check out:

https://github.com/eugeneching/ida-consonance
