### ISSUE TITLE
Have no horizontal scroll bar in many windows under IDA 6.95 & Black theme 

### ISSUE THREAD

**Issue by SilverBut** [zyantific/IDASkins#13]
Will have a pull request later. 

Besides, considering its reason, i think this bug also exists under other IDA 6.x versions.

**Comment by SilverBut** [comment]
Pull request committed.

**Comment by SilverBut** [comment]
The problem seems happened again. 

I've checked the history and seems commit 027c646 and commit 292090d is broken by commit 057fd69, which is referenced in p.r. #17 which imported a new skin.

Since I'm unfamiliar with Qt, it might be a good idea to check new style sheets and see if something wrong.

Thanks. 

@athre0z

**Comment by athre0z** [comment]
We just haven't pushed a new version for many months, thus these changes aren't yet available in the release version. I might push a new version if I find time in the coming few days.

**Comment by SilverBut** [comment]
Oops, just found it. 

I've cloned and applied the new skin from repo. The scroll bar come back again and everything is fine now.

Sorry for such a bother...
