### ISSUE TITLE
Theme doesnt load

### ISSUE THREAD

**Issue by lexlutorr** [zyantific/IDASkins#24]
I cant seem to change the theme , I open IDA and it says ather0z plugins loaded ! But on edit > skins there is no theme loaded , I think is the path , there is no skins directory whatsover , where should be the skins folder be pasted ?

**Comment by athre0z** [comment]
The skin folder needs to be placed in the IDA root. To install the plugin properly, just download the latest release and paste the contents of the directory matching your IDA version into your IDA installation folder.
