### ISSUE TITLE
minor color issue in skin/adwaita-dark/stylesheet.qss

### ISSUE THREAD

**Issue by SubaruDieselCrew** [zyantific/IDASkins#25]
IDA console output:
> QCssParser::parseHexColor: Unknown color name '#00000'

patch for file `skin/adwaita-dark/stylesheet.qss`
```
105c105
<     border: 2px outset #00000;
---
>     border: 2px outset #000000;
```
Did not notice any visual changes but gets rid of above warning.

**Comment by athre0z** [comment]
I didn't notice any error being printed, where did you see that? Nevertheless, since the color code was obviously malformed, I just pushed a fix. Thanks for the report!

**Comment by SubaruDieselCrew** [comment]
No probs. To clarify, the error gets displayed in Linux terminal after launching IDA via command line.
