### ISSUE TITLE
Install IDA skin

### ISSUE THREAD

**Issue by daoduythuan** [zyantific/IDASkins#28]
Hi guys,

Can you write a tutorial how to compile IDASkins and install into IDA?

**Comment by athre0z** [comment]
There is some info here:
https://github.com/zyantific/ida-cmake
However, it's lacking info on how to build on Windows (where stuff is a little more complicated). 

Are you asking for the sake of a 7.0 version?

**Comment by athre0z** [comment]
Since the plugin has been rewritten in Python, compiling it is no longer required.
