### ISSUE TITLE
IDASkins change Hex-Rays Decompiler font to Fixedsys in IDA 7.0

### ISSUE THREAD

**Issue by bruce30262** [zyantific/IDASkins#29]
In IDA 7.0 its default font is changed to Consolas.  
However, while decompiling the binary, the font of the pseudo code is always changed to Fixedsys.  
Restarting or re-installing IDA ( #27 ) doesn't resolve the issue.  

I think the problem is caused by [this line of code](https://github.com/zyantific/IDASkins/blob/master/src/IdaFontConfig.cpp#L48)  
Would you guys fix it ? Thanks

**Comment by athre0z** [comment]
Oh, cool, so HR finally realised that nobody liked Fixedsys. Could you quickly Hex-Edit the string to Consolas and check whether it actually fixes the issue? I don't have decompilers.

**Comment by bruce30262** [comment]
Changing Fixedsys to Consolas fixes the issue :)  ( at least it works on my machine )

**Comment by SilverBut** [comment]
Wondering why we need to return a constant value under Windows. 
Is there any problem if we return another font according to the config file?

**Comment by athre0z** [comment]
What config file are you referring to? The skin manifest? This function obtains the font values set in the IDA settings. If the font wasn't manually changed by the user, the config keys aren't set and we have to fall back to the IDA defaults — which, unless they changed that, happen to be the system default on Unix and `Fixedsys`/`Consolas` on Windows. Thus the constant.

**Comment by SilverBut** [comment]
Oh I know.....
Now I understand why it is a const value.
Thanks.

**Comment by Mem2019** [comment]
Also the size of font is fixed at 10 after restarting, although I have changed the settings before restarting :(
