### ISSUE TITLE
7.0 on Mac

### ISSUE THREAD

**Issue by jags613** [zyantific/IDASkins#30]
We can haz binary for IDA7.0 MacOS? <3

**Comment by Coldzer0** [comment]
i hope it helps 😎 

https://mega.nz/#!U5p3FTzS!Ni2mrOTeS1phJyy4rvxgEWdTLR0fWxQVM6MymGw74cE

**Comment by jags613** [comment]
You're the best. Thank you!

**Comment by athre0z** [comment]
Closing. Plugin has been rewritten in Python — no more platform specific binary fiddling!
