### ISSUE TITLE
i Build IDASkins For Ida Pro 7.0 for Mac OS

### ISSUE THREAD

**Issue by Coldzer0** [zyantific/IDASkins#31]
@athre0z 
i hope it helps 😎  , you can use it on releases ;)

https://goo.gl/NNsqvF

**Comment by athre0z** [comment]
Thanks mate! We generally have a policy of not releasing binaries we didn't build ourselves, but I'll leave this one open until I motivated our Mac IDA guy to build official ones.

**Comment by Daemonceltics** [comment]
Download failed, I don't know why.
![image](https://user-images.githubusercontent.com/14012342/34670954-5ede2ec6-f4b3-11e7-8f82-c90cd1070d4f.png)

**Comment by Daemonceltics** [comment]
My theme is very wired，embarrassed!
![image](https://user-images.githubusercontent.com/14012342/34672913-58a2e710-f4bb-11e7-88d5-31f17b532477.png)

**Comment by athre0z** [comment]
Please check out this: https://github.com/zyantific/IDASkins/issues/1

**Comment by athre0z** [comment]
Closing. Plugin has been rewritten in Python — no more platform specific binary fiddling!
