### ISSUE TITLE
How to build IDASkins for IDA7.0 in MacOS High Sierra 10.13

### ISSUE THREAD

**Issue by ouraigua** [zyantific/IDASkins#33]
These are the steps I took to successfully build IDASkins for IDA 7.0 on my MacOS 10.13 (High Sierra).

`$ git clone https://github.com/zyantific/IDASkins.git`
`$ cd IDASkins`
`$ git clone https://github.com/zyantific/ida-cmake.git`

To build run:
`$ ida-cmake/build.py -i 'path_to_ida_sdk' -t 7.0 --idaq-path '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/' `

If you get an error stating:

> Could not find a package configuration file provided by "Qt5Widgets” etc...

Fix it by installing qt using brew:
`$ brew install qt5`

Locate where it is installed (for me it was **/usr/local/Cellar/qt/5.9.3**) using:
`$ brew info qt5`

Copy the path then modify:
> ./ida-cmake/build.py

by finding the line (#163) where it says: **“if args.idaq_path:”** 
and append this line at (#166):

> cmake_cmd.append('-DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.9.3')

After that try building again:
`$ ida-cmake/build.py -i 'path_to_ida_sdk' -t 7.0 --idaq-path '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/'`

If you need help building IDA7.0 SDK, I'll be happy to share my steps.

I hope this helps someone out there.

PS: Some shots of my version of idaskins-dark. I'm including it for anyone who likes it:
[idaskins-dark.zip](https://github.com/zyantific/IDASkins/files/1503575/idaskins-dark.zip)

  
<img width="1440" alt="screen shot 2017-11-26 at 02 35 20" src="https://user-images.githubusercontent.com/6299112/33236706-ccc0afe0-d253-11e7-96d2-8f38bd4700e6.png">
<img width="1440" alt="screen shot 2017-11-26 at 02 39 01" src="https://user-images.githubusercontent.com/6299112/33236707-ccd975ca-d253-11e7-8a6b-aead6b156459.png">
<img width="1440" alt="screen shot 2017-11-26 at 02 39 32" src="https://user-images.githubusercontent.com/6299112/33236708-ccf1a046-d253-11e7-9014-ddb7baac19d4.png">

**Comment by athre0z** [comment]
Interesting, thanks! 

Actually `build.py` is supposed to pass all non-recognized arguments to CMake, sparing you the manual edit, however it looks like I forgot to actually implement that (having it just swallow them). With Qt5 from MacPorts, it just works out of the box.

**Comment by athre0z** [comment]
Since you also posted it into the Wiki, I'll close this for now.

**Comment by WinMin** [comment]
hello ! why ?
![image](https://user-images.githubusercontent.com/18380453/37594027-0784571c-2baf-11e8-86a6-8f0639930ce8.png)

**Comment by athre0z** [comment]
See #1
