### ISSUE TITLE
Link error on Windows 10 IDA Pro 7.0

### ISSUE THREAD

**Issue by Randshot** [zyantific/IDASkins#34]
Hey, I am trying to compile the latest commit (2646f5e187028923117243e6264b3f18c2947d33) on the dev branch on Windows 10.
I have installed Qt5, but when I try to compile IDASkins, it gives me a linking error:
```
ThemeSelector.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl QT::QListWidget::setSelec
tionModel(class QT::QItemSelectionModel *)" (?setSelectionModel@QListWidget@QT@@UEAAXPEAVQItemSelectionModel@2@@Z)
```
I have tried various Qt5 versions: 5.9.3, 5.9.4 and 5.10
But none compiled successfully, so I think that I am doing something wrong :/

**Edit:**
This is the command I use to compile:
```bash
python .\ida-cmake\build.py -i "../idasdk70" -t 7.0 --idaq-path "A:/IDA 7.0" --skip-install
```

I also just saw this CMake warning, maybe it has to do something with it:
```
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.
  Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the GENERATED source file(s):

    "A:/repos/IDASkins/build-7.0-32/ui_ThemeSelector.h"
    "A:/repos/IDASkins/build-7.0-32/ui_ObjectInspector.h"

  from processing by AUTOMOC.  If any of the files should be processed, set
  CMP0071 to NEW.  If any of the files should not be processed, explicitly
  exclude them by setting the source file property SKIP_AUTOMOC:

    set_property(SOURCE file.h PROPERTY SKIP_AUTOMOC ON)

This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by athre0z** [comment]
On Windows, starting with IDA 7.0, you essentially only use the Qt headers from the Qt installation and link against the binaries that come with the SDK, so the Qt version used should no longer be insanely important. Did you make sure to target X64?

**Comment by Randshot** [comment]
@athre0z I modified the build.py to include `cmake_cmd.append('-DCMAKE_PREFIX_PATH=C:/Qt/5.10.0/msvc2017_64')`

**Comment by athre0z** [comment]
Unfortunately, I can't test this stuff right now since my desktop with my Windows VM broke a few weeks ago and I'm still waiting for mobo replacement from the vendor.

I assume your SDK is original and untouched as shipped by HR?

**Comment by Randshot** [comment]
I assume that it is untouched, at least I didn't modify anything manually, but I will test it again.

**Comment by Randshot** [comment]
@athre0z I think I found the problem.
I just looked at the library imports in the generated IDASkins.vcxproj file and noticed that the Qt5 libraries get imported wrongly:
```
..\idasdk70\lib\x64_win_vc_64\ida.lib
..\idasdk70\lib\x64_win_vc_64\pro.lib
..\idasdk70\lib\x64_win_qt\Qt5Widgets.lib
..\idasdk70\lib\x64_win_qt\Qt5Gui.lib
..\idasdk70\lib\x64_win_qt\Qt5Core.lib
```
I will try fixing it right now.

**Comment by athre0z** [comment]
What's wrong about that? It intentionally links against the Qt libs that ship with IDA.

**Comment by Randshot** [comment]
Ops, I didn't notice that. Hm, is there any difference between the Qt5 libs that IDA ships and the ones you get when installing Qt5?

**Comment by athre0z** [comment]
Yes. HR has a commercial Qt license and have changed various things. Also, it spares you compiling Qt since you only need the headers. It'd be even better if HR would also ship the headers, but nope, they don't. Well, I guess with a project as complex as Qt, that's probably easier said than done.

**Comment by athre0z** [comment]
Also, HR compiles Qt with some non-standard flags, like `QT_NAMESPACE=QT`, so the binary Qt deployments won't work.

**Comment by Randshot** [comment]
Weird is that `QT::QListWidget::setSelectionModel()` doesn't even get used in the IDASkins project, at least the reference search didn't give any results.

**Comment by Randshot** [comment]
Seems like I have found a .. 'solution'.
I just commented the `setSelectionModel()` method out in the `qlistwidget.h` file at line `210`.

**Comment by athre0z** [comment]
Mh, maybe it's in one of the `.cpp` files generated from the `.ui` files or referenced in an inline Qt function. I guess this will have to wait until my PC is back up and running. In the mean time, you might want to just use the binaries.

https://github.com/zyantific/IDASkins/releases

**Comment by Randshot** [comment]
One thing I noticed is that the Font always resets for the 'Pseudocode' window after closing it.
Is that intentional?

**Comment by athre0z** [comment]
I'm not sure what "reset after closing" means. After opening it a second time? That certainly wouldn't be intended, but I'm significantly too broke to spend multiple thousand $ on the decompiler, so you'd have to debug that yourself.

**Comment by Randshot** [comment]
Ok, then I will look at that some time later.
Since this issue is resolved, I will close it now.

Closed.

**Comment by Randshot** [comment]
Also, here is the compiled version for the dev branch.

[IDASkins.zip](https://github.com/zyantific/IDASkins/files/1704182/IDASkins.zip)
