### ISSUE TITLE
Include IDA color schemes with skins

### ISSUE THREAD

**Issue by tostercx** [zyantific/IDASkins#35]
Hey,

how hard would it be to include color schemes (clr files) with the skins and automatically apply them? It's currently a PITA to find the right ones and set them up.

I imagine adding a check box so the user can choose if he wants to apply the skin's clr file or something like that.

**Comment by tostercx** [comment]
Hmm... could include them with the skins at least. Maybe even provide a copyable path to ease installation?

Hadn't noticed, but `idadark-unis` already has a .clr file.

**Comment by athre0z** [comment]
Mh yeah, that would probably help.

**Comment by tostercx** [comment]
Like so?

https://github.com/tostercx/IDASkins/commit/fed18ac83165cbd9e310759667105a42aebbf8d8

<img src="https://user-images.githubusercontent.com/4965387/38532980-cc95c528-3c7f-11e8-8608-abb06d082ece.png" width="500">

**Comment by tostercx** [comment]
Btw I noticed https://github.com/zyantific/IDASkins/issues/32, so we can now write to the "registry" universally. Would converting `clr`s to `reg` entries be enough or is there more platform specific stuff how / where the values are stored?

**Comment by athre0z** [comment]
Sorry for the late response, I completely forgot about this topic. Hm, I don't know, we would to check. However, I don't know if it's really worth the effort. Having a copy & pastable path + maybe a quick hint on how to apply it would probably already help quite a bit while not implementing something that might be a pain to maintain when HR implements changes to the color format. The format did change quite a bit already in the past few years and I really don't feel like updating some registry hack for every version.

**Comment by tostercx** [comment]
I see. So I guess I could add a note on applying the clr and then send a PR?

**Comment by athre0z** [comment]
Yeah, I'd probably just go with adding another line below the CLR path, maybe make it red. But maybe you've got a better idea. Looking forward for the PR. :)

**Comment by athre0z** [comment]
Now merged into master!
