### ISSUE TITLE
No such file or directory: [theme_dir]\\manifest.json

### ISSUE THREAD

**Issue by bruce30262** [zyantific/IDASkins#37]
### Environment  
* Windows 10 Pro 64bit
* IDA 7.0  
* Python 2.7.13

### Detail  
I was trying to update IDASkins to version 2.0.0, so I  
* Delete those dlls in my IDA root/plugins directory  
* Copy the contents of the plugins directory into my IDA root/plugins directory  
* Open an .idb file to see if it work  

Then I found IDA didn't load the IDASkins plugin, and the IDA output windows has the following error message:
```
[Errno 2] No such file or directory: idaskins-dark\\manifest.json
```  

So I print out the `theme_dir` variable in `apply_stylesheet_from_settings()`, and the output is:  
`idaskins-dark`  

To resolve the issue, I copied the `idaskins-dark` directory into my working directory.  
Now it successfully load the IDASkins plugin,  and the error message no longer appear.  

More strangely, I tried to delete the `idaskins-dark` directory to reproduce the issue, and found that now the `theme_dir` variable has been set to `C:\Program Files\IDA 7.0\plugins\idaskins\themes\idaskins-dark`, not `idaskins-dark` anymore, so now I can't reproduce the issue :/  

------------------------------

Although this is no longer an issue for me, I feel like I'm still going to report this:  
For some unknown reason, `theme_dir` will be set to a relative path while updating IDASkins, causing the plugin failed to load the manifest file.  

It would be nice if we can identify and fix the issue so everyone can happily update to version 2.0.0  
Any thoughts ?

**Comment by athre0z** [comment]
Thanks for letting me know! Looks like the old versions stored a relative path instead of an absolute one. Thinking about it, it's probably a better idea to revert those relative pathes since people might be moving their IDA root around. I think I'll revert to using relative pathes and add a detection for existing settings with absolute pathes for those folks that already updated to v2.0.

**Comment by athre0z** [comment]
It should be resolved on `develop`. I'll probably release `v2.0.1` pretty soon since this will most likely affect a lot of users.
