### ISSUE TITLE
Empty selectedThemeDir causes the plugin to fail to load

### ISSUE THREAD

**Issue by geneccx** [zyantific/IDASkins#38]
` 
File "plugins\idaskins\settings.py", line 15, in selected_theme_dir
    return self._settings.value(SELECTED_THEME_DIR_KEY, None).encode()
AttributeError: 'NoneType' object has no attribute 'encode'
`

Since the setting defaults to None, calling `encode()` causes the plugin to blow up, and makes it impossible to select a theme since it won't load. I've found that defaulting to an empty string works fine, and allows me to set a theme after the plugin successfully loads.

On a related note: when I was prompted to select a theme on first run, I pressed yes and the theme selection window popped up briefly and immediately disappeared.

This was what caused this bug for me in the first place, although this may be due to a plugin conflict or some other factors. I haven't had the chance to figure out exactly what causes this.

Declining the first run theme selection causes the same issue.

**Comment by athre0z** [comment]
Whoops, guess I should have tested that. Thanks for letting me know, should be fixed on develop branch!

**Comment by geneccx** [comment]
Sure am. It's a small world! I'm glad you're getting good mileage out of it. I actually stumbled upon this project while looking for other IDA plugins.

Keep up the great work!

**Comment by athre0z** [comment]
Excellent! I just released `v2.0.2`, since, just like `v2.0.1`, the issue probably affected a lot of users.
