### ISSUE TITLE
FIRST_START_KEY and macOS

### ISSUE THREAD

**Issue by melomac** [zyantific/IDASkins#42]
Many thanks for IDASkins. I use it on macOS for some years now and this update really ease the installation 😅

Every time I launched IDA Pro, the _First start_ message welcomed me.  It turns out PyQt returns a Boolean for this `QSettings` on macOS:

```
[IDASkins] v2.0 by athre0z (zyantific.com) loaded!
[IDASkins] Skin file successfully applied!
Python>from PyQt5.QtCore import QSettings
Python>_settings = QSettings("athre0z", "IDASkins")
Python>FIRST_START_KEY = 'firstStart'
Python>_settings.value(FIRST_START_KEY, True)
False
```

I already fixed the issue on my side, but I wanted to follow up on your comment and let you know how it works with macOS:
https://github.com/zyantific/IDASkins/blob/3d96fbb823f1483489d1132613098b889117a4ed/plugins/idaskins/settings.py#L25-L26

Thanks!

**Comment by athre0z** [comment]
It seems rather stupid for a cross-platform lib to return different types on different platforms. Damn PyQt. Thanks for letting me know!
