### ISSUE TITLE
prompt "IDASkins detected that this is you first IDA..." all the time in IDA pro 7.1

### ISSUE THREAD

**Issue by menglong2234** [zyantific/IDASkins#44]
I just comment this part of the plugin to handle this ...

**Comment by athre0z** [comment]
Platform, Plugin version?

**Comment by athre0z** [comment]
Please check if this issue is resolved when downloading the latest code from master. I merged a fix for macOS about an month ago, however didn’t do a new release yet. I think it might address your issue.

**Comment by menglong2234** [comment]
Thx！
