### ISSUE TITLE
IDA Pro 7.2 Navigation toolbar and QPushButton

### ISSUE THREAD

**Issue by melomac** [zyantific/IDASkins#46]
https://github.com/zyantific/IDASkins/blob/a078e1e164d4002ff06a47441893e37a89a3a0e4/plugins/idaskins/themes/idaskins-dark/stylesheet.qss#L128-L129

On IDA Pro 7.2 beta 1, the Navigation toolbar `nav_scroll_button_t` buttons are affected by the size constraints of `QPushButton` style.

As a result, the toolbar is much bigger than expected.

IDA Pro 7.1:
![image](https://user-images.githubusercontent.com/1131386/47426999-4f910780-d78f-11e8-9d6f-10d7c83b85d8.png)

IDA Pro 7.2:
![image](https://user-images.githubusercontent.com/1131386/47427006-5586e880-d78f-11e8-8f27-b37e29d08095.png)

**Comment by athre0z** [comment]
I think I'll wait for the final to arrive before addressing this. Don't want to bother the HR people with a beta request when the release of the final is probably just around the corner. If you want to look into it yourself, you are obviously very welcome to and I'd be happy to merge a PR!

**Comment by athre0z** [comment]
Fixed on master. Thanks for reporting this!
