### ISSUE TITLE
IDA always prompting "IDASkins detected that this is you first IDA startup with this plugin installed...."

### ISSUE THREAD

**Issue by racterub** [zyantific/IDASkins#48]
Found same issue: #44 

I am using newest version of IDASkins (Commit a078e1e164d400).
Env:
- Mac OSX 10.14 Mojave
- IDA Pro 7.0

**Comment by athre0z** [comment]
I think this might be a duplicate of #44 -- could you check?

**Comment by racterub** [comment]
OK, I might did something dumb :p 
Solved..
