### ISSUE TITLE
IDA always displays an error message no module PyQt5

### ISSUE THREAD

**Issue by bhrdn** [zyantific/IDASkins#50]
Hello everyone, is there a solution to install idaskins on ubuntu 16??, IDA always displays an error message, when it was first opened, even though I installed the PyQt5 module.

![screenshot from 2018-11-30 06-43-36](https://user-images.githubusercontent.com/13828056/49260169-f2176700-f46e-11e8-8284-7765bef64787.png)
![screenshot from 2018-11-30 06-45-56](https://user-images.githubusercontent.com/13828056/49260172-f774b180-f46e-11e8-82e0-a23c253507c0.png)

**Comment by athre0z** [comment]
IDA 6.8 is not supported by the Python version of the plugin. You'll have to switch back to one of the earlier `v1.X` versions still written in C++ to make it work.
