### ISSUE TITLE
IDA 7 64 bit?

### ISSUE THREAD

**Issue by cclamb** [zyantific/IDASkins#51]
So I've installed the code in the plugins directory, but when I start IDA, it doesn't seem to have any effect. I copied the contents over to plugins, so that we have plugins/idaskins.py and plugins/idaskins/*.

Is there a configuration panel I don't know about or something? Thanks so much!

**Comment by athre0z** [comment]
What is your platform and exact IDA version?

**Comment by cclamb** [comment]
Was using wrong Plugins file. Need to use the one in MacOS, not under Contents.

**Comment by cclamb** [comment]
Sorry Joel, I figured it out; there's two plugin directories and I put the
code in the wrong one. Thanks for following up though.

**Comment by eyalSemel** [comment]
Hey Chris, could you elaborate on what two plugin directories are there? I think I have a similar issue but I don't know what/where the other plugins directory is.

**Comment by n0irx** [comment]
@eyalSemel 

Do you use Mac? If so, you should put the plugin on `<IDA Pro Folder>/Contents/MacOS/plugins` instead of `<IDA Pro Folder>/Contents/PlugIns`; it works for me.

I hope it can help you.

**Comment by cclamb** [comment]
Thanks much! I'll give it a shot.
