### ISSUE TITLE
IDA doesn't load the plugin

### ISSUE THREAD

**Issue by hustwyk** [zyantific/IDASkins#54]
System: MacOS 10.14.3
IDA Pro version: 7.0.170914
I have copied the contents of the _plugins_ directory into the _plugins_ directory of my IDA installation. But when I restart my IDA Pro 32bit or 64bit, I cannot find the plugin under my **Edit->Plugins**

**Comment by athre0z** [comment]
Could this be a similar issue as in #51?

**Comment by hustwyk** [comment]
> Could this be a similar issue as in #51?

yes, that's the exact problem I met, I copied the wrong folder...emmm, I didn't know there exist two _plugins_ folders...anyway, thank you :)

**Comment by athre0z** [comment]
No problem!
