### ISSUE TITLE
Missing Toolbar Handle for VSCode when Vertical

### ISSUE THREAD

**Issue by 2yangk23** [zyantific/IDASkins#61]
Currently there is only `QToolBar:handle` and it is configured in a way to show the handle for the horizontal toolbar. When dragging the toolbar to its vertical orientation, the handle does not show and you are unable to drag the toolbar.

Should instead have separate:
```
QToolBar:handle:horizontal
QToolBar:handle:vertical
```

**Comment by athre0z** [comment]
Should be fixed in @Jinmo's PR -- thanks for reporting!
