### ISSUE TITLE
Using version 1.3.0 on IDA Pro 6.8

### ISSUE THREAD

**Issue by CodysGithub** [zyantific/IDASkins#65]
Hey there, so I'm using the release version 1.3.0 on IDA Pro 6.8 since the latest version didn't seem to work for it. I'm wondering if there's a way for me to get the VS-Code Theme that you have on the latest version for me even though I'm not running the latest version I tried just taking the folder vscode-dark and putting it in the skins directory but unfortunately it didn't recognize it as a skin in IDA. Any hope for me to be able to get the vscode-dark theme I fucking love it to death.

**Comment by athre0z** [comment]
Hey, you'd have to back-port the theme manually. That would mainly consist of translating the JSON manifest file to XML (you can use the other templates as reference). Aside from that, I don't think that incredibly much changed.

**Comment by CodysGithub** [comment]
> 
> 
> Hey, you'd have to back-port the theme manually. That would mainly consist of translating the JSON manifest file to XML (you can use the other templates as reference). Aside from that, I don't think that incredibly much changed.

Love you, was able to do it in less than five minutes. My IDA Pro looks nice as fuck now.

**Comment by CodysGithub** [comment]
@athre0z Is there a way to make the text bigger and everything else? I have a 2560x1440 screen and in this image everything seemed like a good size for my eyes but after loading it up in my IDA it seems wayy smaller here's a comparison.

Your image:
https://raw.githubusercontent.com/athre0z/ida-skins/master/media/screenshots/vscodetheme1.png

My image:
https://i.imgur.com/UP3BFPB.png

**Comment by athre0z** [comment]
https://www.hexblog.com/?p=1180

Also, your font is messed up -- you'll probably have to fix some stuff in the CSS file. Also, restart IDA at least once after applying a new theme.

**Comment by CodysGithub** [comment]
> 
> 
> https://www.hexblog.com/?p=1180
> 
> Also, your font is messed up -- you'll probably have to fix some stuff in the CSS file. Also, restart IDA at least once after applying a new theme.

Alright, thanks.

**Comment by CodysGithub** [comment]
I appreciate the help @athre0z, but I feel like there's to many problems. Good works though, I love your themes. Especially the VSCode one, if I ever go up to IDA Pro 7.3 or anything I'll make sure to use it.

**Comment by CodysGithub** [comment]
I actually found a good middle ground. Using the .clr file for vscode and then the dark theme provided in IDASkins 1.3.0 I was able to make my IDA still look good with the amazing blue. Thanks
