### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by awesomennguy** [zyantific/IDASkins#68]
Not working,
I copied the contents of the "plugins" directory into the "plugins" directory in IDA and then nothing appeared in Edit->Plugins

**Comment by athre0z** [comment]
IDA version, OS?

**Comment by awesomennguy** [comment]
IDA 7.2, Windows

**Comment by athre0z** [comment]
Well, that is definitely a confirmed working target, so it must be a problem with how you install it. Does IDAPython in general work? Any errors in IDA's output windows?
